[package]
name = "vql-testing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
system-tests = []

[dev-dependencies]
arrow.workspace = true
libtest-mimic.workspace = true
rdkafka.workspace = true
sqllogictest.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
vql-kernel = { path = "../vql-kernel" }

[[test]]
name = "slt"
path = "tests/slt.rs"
harness = false
required-features = ["system-tests"]

[[test]]
name = "rtsp"
path = "tests/rtsp.rs"
harness = false
required-features = ["system-tests"]

[[test]]
name = "kafka"
path = "tests/kafka.rs"
harness = false
required-features = ["system-tests"]
