[package]
name = "vql-testing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
system-tests = []

[dev-dependencies]
arrow.workspace = true
arrow-flight.workspace = true
futures.workspace = true
libtest-mimic.workspace = true
prost.workspace = true
rdkafka.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-stream = { version = "0.1", features = ["net"] }
tonic.workspace = true
vql-kernel = { path = "../vql-kernel" }
vql-server = { path = "../vql-server" }

[[test]]
name = "image"
path = "tests/image.rs"
harness = false
required-features = ["system-tests"]

[[test]]
name = "video"
path = "tests/video.rs"
harness = false
required-features = ["system-tests"]

[[test]]
name = "model"
path = "tests/model.rs"
harness = false
required-features = ["system-tests"]

[[test]]
name = "rtsp"
path = "tests/rtsp.rs"
harness = false
required-features = ["system-tests"]

[[test]]
name = "kafka"
path = "tests/kafka.rs"
harness = false
required-features = ["system-tests"]

[[test]]
name = "vqld"
path = "tests/vqld.rs"
harness = false
required-features = ["system-tests"]
