[package]
name = "vql-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["http", "sqlite"]
http = ["dep:axum"]
sqlite = ["dep:rusqlite"]

[dependencies]
arrow.workspace = true
axum = { workspace = true, optional = true }
chrono.workspace = true
rusqlite = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
tower.workspace = true
